# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_methods_pb2 as rpc__methods__pb2


class GetSearchStub(object):
    """定义一个调用爬虫的服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchInfo = channel.unary_unary(
                '/pb.GetSearch/SearchInfo',
                request_serializer=rpc__methods__pb2.Params.SerializeToString,
                response_deserializer=rpc__methods__pb2.Res.FromString,
                )


class GetSearchServicer(object):
    """定义一个调用爬虫的服务
    """

    def SearchInfo(self, request, context):
        """python项目的 SearchInfo方法
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchInfo,
                    request_deserializer=rpc__methods__pb2.Params.FromString,
                    response_serializer=rpc__methods__pb2.Res.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.GetSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetSearch(object):
    """定义一个调用爬虫的服务
    """

    @staticmethod
    def SearchInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.GetSearch/SearchInfo',
            rpc__methods__pb2.Params.SerializeToString,
            rpc__methods__pb2.Res.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
