# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_methods.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc_methods.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11rpc_methods.proto\x12\x02pb\"\x15\n\x06Params\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x12\n\x03Res\x12\x0b\n\x03res\x18\x01 \x01(\t20\n\tGetSearch\x12#\n\nSearchInfo\x12\n.pb.Params\x1a\x07.pb.Res\"\x00\x62\x06proto3'
)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='pb.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='pb.Params.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=46,
)


_RES = _descriptor.Descriptor(
  name='Res',
  full_name='pb.Res',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='pb.Res.res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
DESCRIPTOR.message_types_by_name['Res'] = _RES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'rpc_methods_pb2'
  # @@protoc_insertion_point(class_scope:pb.Params)
  })
_sym_db.RegisterMessage(Params)

Res = _reflection.GeneratedProtocolMessageType('Res', (_message.Message,), {
  'DESCRIPTOR' : _RES,
  '__module__' : 'rpc_methods_pb2'
  # @@protoc_insertion_point(class_scope:pb.Res)
  })
_sym_db.RegisterMessage(Res)



_GETSEARCH = _descriptor.ServiceDescriptor(
  name='GetSearch',
  full_name='pb.GetSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=68,
  serialized_end=116,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchInfo',
    full_name='pb.GetSearch.SearchInfo',
    index=0,
    containing_service=None,
    input_type=_PARAMS,
    output_type=_RES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSEARCH)

DESCRIPTOR.services_by_name['GetSearch'] = _GETSEARCH

# @@protoc_insertion_point(module_scope)
